name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  publish:
    name: Publish package to NPM
    runs-on: [ubuntu-latest]
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to NPM
        run: npm publish --access public
